name: Run Script

on:
  schedule:
    - cron: "5,10,15,20,25,30,35,40,45,50,55 * * * *" # Executes on Mondays at 12pm UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    # runs-on: denoland/deno:ubuntu-1.35.2
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Print Contents
        run: "ls -al"

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.2
        with:
          deno-version: v1.x
      - name: Check Deno Version
        run: "deno --version"
      - name: Run script
        run: |
          deno run --allow-read --allow-net --allow-env ./main.ts
