name: Run Script

on:
  schedule:
    - cron: "5,10,15,20,25,30,35,40,45,50,55 * * * *" # Executes on Mondays at 12pm UTC

jobs:
  run-script:
    runs-on: denoland/deno:ubuntu-1.35.2
    steps:
      - name: Check Deno Version
        run: "deno --version"
      - name: Checkout Repo
        run: actions/checkout@v3

      - name: Run script
        run: |
          deno --allow-read --allow-net --allow-env ./main.ts
